CREATE TABLE STUDENTS
(
		StuID INT,
		FirstName VARCHAR(25),
		LastName VARCHAR(25),
		Website VARCHAR(50),
		City VARCHAR(25),
		Division VARCHAR(20)
)

SELECT * FROM STUDENTS

INSERT INTO STUDENTS VALUES (1011,'KEYUR','PATEL','techonthenet.com','RAJKOT','II-BCX')
INSERT INTO STUDENTS VALUES (1022,'HARDIK','SHAH','DIGMINECRAFT.com','Ahmedabad','I-BCy')
INSERT INTO STUDENTS VALUES (1033,'KAJAL','TRIVEDI','BIGACTIVITIES.com','Baroda','IV-DCX')
INSERT INTO STUDENTS VALUES (1044,'BHOOMI','GAJERA','CHECKYOURMATH.com','Ahmedabad','III-DCW')
INSERT INTO STUDENTS VALUES (1055,'HARMIT','MITEL',NULL,'Rajkot','II-BCY')
INSERT INTO STUDENTS VALUES (1066,'ASHOK','JANI',NULL,'Baroda','II-BCZ')

SELECT * FROM STUDENTS
	WHERE FirstName LIKE 'K%';

SELECT * FROM STUDENTS
	WHERE FirstName LIKE  '_____';

SELECT FirstName , LastName FROM STUDENTS
	WHERE CITY LIKE '%a' AND CITY LIKE '______';
	
SELECT * FROM STUDENTS
	WHERE LastName LIKE '%tel';

SELECT * FROM STUDENTS
	WHERE FirstName LIKE 'HA%' AND FirstName LIKE '%T';

SELECT * FROM STUDENTS
	WHERE FirstName LIKE 'K_Y%';

SELECT * FROM STUDENTS
	WHERE WEBSITE IS NULL AND FirstName LIKE '_____';
	
SELECT * FROM STUDENTS
	WHERE LastName LIKE '%JER%';

SELECT * FROM STUDENTS
	WHERE CITY LIKE 'R%' OR CITY LIKE 'B%'; 
	
SELECT * FROM STUDENTS
	WHERE WEBSITE IS NOT NULL;

SELECT * FROM STUDENTS
	WHERE FirstName LIKE '[A-H]%';

SELECT * FROM STUDENTS
	WHERE FirstName LIKE '_[A,E,I,O,U]%';	

SELECT * FROM STUDENTS
	WHERE CITY LIKE '%ROD%';

SELECT FirstName , LastName FROM STUDENTS
	WHERE WEBSITE LIKE 'BI%';
	
SELECT CITY FROM STUDENTS WHERE LastName LIKE '______';

SELECT * FROM STUDENTS WHERE CITY LIKE '_____' AND CITY NOT LIKE 'BA%';

SELECT * FROM STUDENTS WHERE Division LIKE 'II%';

SELECT FirstName,Division FROM STUDENTS WHERE Division LIKE '%B%C%';	

SELECT StuID,CITY FROM STUDENTS WHERE DIVISION LIKE '______' AND Website IS NOT NULL;

SELECT * FROM STUDENTS WHERE FirstName NOT LIKE '___[AEIOU]%';
