CREATE TABLE STUDENTS
(				ENROLLMENT_NO VARCHAR(20),
				NAME VARCHAR(25),
				CPI DECIMAL(5,2),
				BIRTHDATE DATETIME
)

SELECT * FROM STUDENTS

ALTER TABLE STUDENTS
	ADD CITY VARCHAR(20) NULL,
		BACKLOG INT NOT NULL;

ALTER TABLE STUDENTS
	ALTER COLUMN NAME VARCHAR(35);

ALTER TABLE STUDENTS
	ALTER COLUMN CPI INT;

SP_RENAME 'STUDENTS.ENROLLMENT',
			'ENO';

ALTER TABLE STUDENTS
	DROP COLUMN CITY;

ALTER TABLE STUDENTS
	DROP COLUMN BACKLOG;

ALTER TABLE STUDENTS
ALTER COLUMN NAME VARCHAR(35) NOT NULL

SP_RENAME 'STUDENTS.BIRTHDATE' , 'BDate';


ALTER TABLE STUDENTS
ALTER COLUMN ENO VARCHAR(12);

SP_RENAME 'STUDENTS',
			'STUDENTS_MASTER';










