CREATE DATABASE YASH_21010101106


CREATE TABLE Student_Marks
(					Sid INT NOT NULL,
					SName VARCHAR(50) NOT NULL,
					Marks INT NOT NULL
)

SELECT * FROM Student_Marks

INSERT INTO Student_Marks VALUES(1,'JOHN',90)
INSERT INTO Student_Marks VALUES(2,'MARTIN',80)
INSERT INTO Student_Marks VALUES(3,'CAROL',89)
INSERT INTO Student_Marks VALUES(4,'JACK',99)
INSERT INTO Student_Marks VALUES(5,'ROSE',88)
INSERT INTO Student_Marks VALUES(6,'MARY',90)

-- DATE FUNCTION

SELECT GETDATE();

SELECT GETDATE()+365;

SELECT CONVERT(VARCHAR,GETDATE());

SELECT CONVERT(VARCHAR,GETDATE(),106);

SELECT CONVERT(VARCHAR,GETDATE(),7);

SELECT DATEDIFF(MONTH,'31-DEC-2008','10-MARCH-2009');

SELECT DATEDIFF(YEAR,'31-DEC-2008','10-MARCH-2009');

SELECT DATEDIFF(HOUR,'31-DEC-2008','31-MARCH-2009');

SELECT DAY('12/MAY/2016');

SELECT MONTH('12/MAY/2016');

SELECT YEAR('12/MAY/2016');

SELECT DATENAME(MONTH,GETDATE());

SELECT DATEPART(MONTH,GETDATE());

SELECT DATEADD(YEAR,5,GETDATE());

SELECT DATEADD(MONTH,-2,GETDATE());

SELECT EOMONTH(GETDATE());

SELECT DATEADD(DAY,30,GETDATE());

SELECT DATEDIFF(YEAR,'26-07-2004',GETDATE());
SELECT DATEDIFF(MONTH,'26-07-2004',GETDATE());
SELECT DATEDIFF(DAY,'26-07-2004',GETDATE());



SELECT COUNT(*) FROM Student_Marks

SELECT SUM(Marks) FROM Student_Marks

SELECT AVG(Marks) FROM Student_Marks

SELECT MIN(Marks) FROM Student_Marks

SELECT MAX(Marks) FROM Student_Marks
					
					