CREATE TABLE Computer
(			RollNo INT,
			Name VARCHAR(20)
)


CREATE TABLE Electrical
(			RollNo INT,
			Name VARCHAR(20)
)

SELECT * FROM Electrical;

SELECT * FROM Computer;

INSERT INTO Computer VALUES(101,'AJAY');
INSERT INTO Computer VALUES(109,'HARRSH');
INSERT INTO Computer VALUES(115,'MANISH');
INSERT INTO Electrical VALUES(105,'AJAY');
INSERT INTO Electrical VALUES(107,'MAHESH');
INSERT INTO Electrical VALUES(115,'MANISH');


SELECT NAME FROM Computer UNION
SELECT NAME FROM Electrical;

SELECT NAME FROM Computer UNION ALL
SELECT NAME FROM Electrical;

SELECT NAME FROM Computer INTERSECT
SELECT NAME FROM Electrical;

SELECT NAME FROM Computer EXCEPT
SELECT NAME FROM Electrical;

SELECT NAME FROM Electrical EXCEPT
SELECT NAME FROM Computer;

SELECT * FROM Computer UNION ALL
SELECT * FROM Electrical;

SELECT * FROM Computer INTERSECT
SELECT * FROM Electrical;


---INTO---

CREATE TABLE Criclet
(			Name VARCHAR(50),
			City VARCHAR(50),
			AGE INT
)

SELECT * FROM Criclet;

INSERT INTO Criclet VALUES('SACHIN TENDULKAR','MUMBAI',30);
INSERT INTO Criclet VALUES('RAHUL DRAVID','BOMBAY',35);	
INSERT INTO Criclet VALUES('M.S.DHONI','JHARKHAND',31);
INSERT INTO Criclet VALUES('SURESH RAINA','GUJARAT',30);

SELECT * INTO WORLDCUP FROM Criclet
SELECT * FROM Criclet;

SELECT Name,City INTO T21 FROM Criclet
SELECT * FROM T21;

SELECT * INTO IPL FROM Criclet;
SELECT * FROM IPL;

INSERT INTO IPL SELECT * FROM Criclet WHERE NAME LIKE '_A_____';
SELECT * FROM IPL;

TRUNCATE TABLE IPL;

DELETE FROM Criclet WHERE City = 'JHARKHAND';

SP_RENAME 'IPL','IPL2018';

DROP TABLE T21;
			

