CREATE DATABASE _YASH21010101106_YASH 

CREATE TABLE STUDENTS
(			RNO INT,
			NAME VARCHAR(50),
			BRANCH VARCHAR(50),
			SPI DECIMAL(4,2),
			BKLOG INT
)

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS VALUES(101,'RAJU','CE',8.80,0);
INSERT INTO STUDENTS VALUES(102,'AMIT','CE',2.20,3);
INSERT INTO STUDENTS VALUES(103,'SANJAY','ME',1.50,6);
INSERT INTO STUDENTS VALUES(104,'NEHA','EC',7.65,1);
INSERT INTO STUDENTS VALUES(105,'MEERA','EE',5.52,2);
INSERT INTO STUDENTS VALUES(106,'MAHESH','EC',4.50,3);

--1--
CREATE VIEW vwPERSNOAL
AS
SELECT * FROM STUDENTS;

SELECT * FROM vwPERSNOAL;

--2--
CREATE VIEW vwSTUDENT_DETAILS
AS
SELECT NAME,BRANCH,SPI FROM STUDENTS;

SELECT * FROM vwSTUDENT_DETAILS;

--3--
CREATE VIEW ACADEMIC
AS
SELECT RNO,NAME,BRANCH FROM STUDENTS;
SELECT * FROM ACADEMIC;

--4--
CREATE VIEW STUDENT_DATA
AS
SELECT * FROM STUDENTS
WHERE BKLOG>2;
SELECT * FROM STUDENT_DATA;

--5--
CREATE VIEW STUDENT_PATTERN
AS
SELECT RNO,NAME,BRANCH FROM STUDENTS
WHERE NAME LIKE '____';
SELECT * FROM STUDENT_PATTERN;

--6--
INSERT INTO ACADEMIC VALUES(101,'MEET','ME');
SELECT * FROM ACADEMIC;

--7--
UPDATE vwSTUDENT_DETAILS
SET BRANCH = 'ME'
WHERE NAME = 'AMIT' AND BRANCH = 'CE';
SELECT * FROM vwSTUDENT_DETAILS;

--8--
DELETE FROM STUDENTS WHERE RNO = 104;
SELECT * FROM STUDENTS;

--9--
CREATE VIEW SPIABOVE9_8
AS
SELECT * FROM STUDENTS WHERE SPI>9.8;
SELECT * FROM SPIABOVE9_8;

--10--
CREATE VIEW BKLOG0
AS
SELECT * FROM STUDENTS WHERE BKLOG  = 0;
SELECT * FROM BKLOG0;